---
abstract: 'rename functions and variables in a PPI::Document using Acme::MetaSyntactic'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::PPIx::MetaSyntactic
name: Acme-PPIx-MetaSyntactic
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Acme::MetaSyntactic: 1.000
  Acme::MetaSyntactic::haddock: 0
  Moo: 1.002000
  PPI: 1.215
  Perl::Critic::Utils: 1.118
  Type::Utils: 0.001
  Types::Standard: 0.001
  namespace::sweep: 0.006
  perl: 5.10.1
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Acme-PPIx-MetaSyntactic
  homepage: https://metacpan.org/release/Acme-PPIx-MetaSyntactic
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-acme-ppix-metasyntactic
version: 0.002
